### ISSUE TITLE
Add geocoder

### ISSUE THREAD

**Issue by Robinlovelace** [cruse-bike/cruse#1]
This to test my understanding of Svelte + maplibre and illustrate the benefits of using a web framework compared with the previous approach of generating .js + HTML files with high level wrappers, currently on the cruse.bike website.

Problem statement: there is currently no Geocoder in the site at https://cruse-bike.github.io/cruse/:

![image](https://github.com/cruse-bike/cruse/assets/1825120/03bd94cf-ffd8-4958-a3d7-0587874cc60b)

Even though there is a nice full screen button and other things thanks to `svelte-maplibre`.

What I'd like to add is something like this:

![image](https://github.com/cruse-bike/cruse/assets/1825120/ab81afa0-5713-41a2-9e80-e9687b75f265)

Source: https://acteng.github.io/atip/browse.html?style=dataviz#6.65/54.389/-1.973

Code that generates that is in https://github.com/acteng/atip/blob/main/src/lib/common/Geocoder.svelte and expressed in the 

`<Maplibre` bit as 

```svelte 
      <Geocoder />
```

Source: https://github.com/acteng/atip/blob/main/src/pages/BrowseSchemes.svelte#L90

I'm going to have a play with this, heads-up @dabreegster who's work inspired my attempts with Svelte + Maplibre.

**Comment by Robinlovelace** [comment]
Just found this, will follow that as 1st port of call: https://docs.maptiler.com/svelte/maplibre-gl-js/geocoding-control/

**Comment by dabreegster** [comment]
Nice! Maptiler has an NPM package and a way to use this without Svelte; it shouldn't be hard to integrate with a vanilla JS app. After about a year of doing web dev, I would definitely recommend Svelte or similar to organize large web apps.

**Comment by Robinlovelace** [comment]
![image](https://github.com/cruse-bike/cruse/assets/1825120/48e5c1d5-600b-427e-9555-01073836d9fc)

**Comment by Robinlovelace** [comment]
Update: the `GeoCoding` element is working, in terms of appearing and allowing users to find a place (add your API key to see it working), with these lines of code:

```
    <GeocodingControl
        apiKey={apiKey}
        position="top-left"
        placeholder="Search for a place"
        limit={5}
        language="en"
        onselect={(event) => {
            console.log(event.detail);
        }}
    />
```

Source: https://github.com/cruse-bike/cruse/blob/main/src/routes/%2Bpage.svelte

Unfortunately, it fails to navigate to the place you've searched for as it does in this demo: https://docs.maptiler.com/svelte/maplibre-gl-js/geocoding-control/ as you'll see here in the deployed demo app from the repo above: https://cruse-bike.github.io/cruse/ (you need to run it locally with an API key to see the results). Not sure next step to get it working, these are the relevant lines of code:
